CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(40) NOT NULL,
  favorite_color VARCHAR(15) NOT NULL
);

INSERT INTO users
  (name, favorite_color)
VALUES
  ('Ines', 'Yellow'),
  ('Lucas', 'Blue'),
  ('Andrea', 'Purple'),
  ('Ingo', 'Black');